version: "3.8"

volumes:
  postgis_data:

services:
  postgis:
    image: postgis/postgis:latest
    shm_size: 2g
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
      POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./compose-entrypoint.d/postgis-create-opendataindex-schema.sql:/docker-entrypoint-initdb.d/11-create-opendataindex-schema.sql
    ports:
      # for local dev, do not expose in production
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G

  # Run with `docker compose run --rm import-sample-data` to import or re-import the sample datasets
  import-sample-data:
    image: osgeo/gdal:alpine-small-3.6.3
    depends_on:
      - postgis
    environment:
      POSTGRES_HOST: postgis
      POSTGRES_DB: postgis
      POSTGRES_SCHEMA: opendataindex
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
    volumes:
      - ./src/services/ogc-features/src/main/resources/sample-data:/sample-data
      - ./compose-entrypoint.d/gdal-import-sample-data.sh:/import-sample-data.sh
    deploy:
      mode: replicated
      replicas: 0
    command: /import-sample-data.sh
    
  ogc-features:
    image: georchestra/data-api:latest
    depends_on:
      - postgis
    environment:
      SPRING_PROFILES_ACTIVE: postgis
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgis
      POSTGRES_SCHEMA: opendataindex
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
      POSTGRES_POOL_MAXSIZE: 20
      POSTGRES_POOL_MINSIZE: 0
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 1G

